In [1]:
import numpy as np
from numpy import save
import rebound
import random
from multiprocessing import Pool
from myfunctions import SimulationLL as simL
import matplotlib.pyplot as plt
from myfunctions import Plotting0




def HW_crit(e,m):
    # eq 3. from H&W(1999)
    # e,m = eb, mu
    a_crit = 1.6 + 5.1*e - 2.22*e**2 + 4.12*m - 4.27*e*m - 5.09*m**2 + 4.61*e**2*m**2
    return a_crit

if __name__ == "__main__":
    random.seed(1)
    
    #10,20,1,15
    Na1, Na2 = 10, 6
    Ne, Na,Nmu,Np = 10,Na1+(Na2*2)-2,1,15 #Np = number of test particles per (eb,ap)tuple 
#     Ne,Na, Nmu, Np =  1,2,1,2
    #Na = 50
    ab = 1
#     ebs = np.array([0])

    ebs = np.linspace(0.,0.9,Ne) #changed from 0.7 to 0.9 (07/28/22)
    aps = ab*np.linspace(1.,5.,Na)
    mus = np.array([0.5])
 
#     params = [(eb,ap,mu,Np) for eb in ebs for ap in aps for mu in mus]
    params = []
    
    a_array = np.zeros((Na,Ne))
    e_array = np.zeros((Na,Ne))
    
    print(a_array)
    print(e_array)
    
    for i,e in enumerate(ebs):
        for j,mu in enumerate(mus):
            ac = HW_crit(e,mu)
            upper, lower = ac*1.15, ac*0.75
            av = np.append(np.linspace(1.,lower, Na2)[:-1],np.linspace(lower,upper,Na1))
            av = np.append(av, np.linspace(upper, 5.,Na2)[1:])
#             for a in av:
            for a,k in enumerate(av):
                params.append((e,a,mu,Np))
                a_array[i,k] = a
                e_array[i,k] = e
    
    print(a_array)
    print(e_array)
    print(params)            
#     np.save('param_vals.npy',params)
#     nproc = 16 # set to (total = nodes*ppn)
    pool = rebound.InterruptiblePool(processes = 16) #add number of processors same as number requested on Sunnyvale  
    
    import time
    import itertools
    start = time.time()
    num = 1
    for _ in itertools.repeat(None,num):
        stime = pool.map(simL.SimulationLL,params) #survival times
    end = time.time()
    print("Time elapsed in minutes is {}".format((end-start)/60.0))
    
    #print(stime)
    #print(stime.shape)
#     save('stime_eb25_ap25_Mu0.5_Np30_logsp0.npy',stime)

    stime = np.array(stime).reshape([Ne,Na,Nmu,Np])
    stime = np.nan_to_num(stime)
    #stime = stime.T
    print(stime)
    print(stime.shape)
    
#     save('stime_eb25_ap25_Mu0.5_Np30_logsp1.npy',stime)
#     save('STIME_PRACTICE_maxdist_20**2_(1,50,1,30).npy',stime)
#     save('stime_practice_maxdist_20_(10,30,1,50).npy',stime)
          

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [ ]:
# ee,aa = np.array(params)[:,0],np.array(params)[:,1]
# # c=np.mean(stime)

# print(params)
# print(len(params))
# print(stime)
# print(len(stime))
# # print(len(ee))
# # # print(ee)
# # print(len(aa))
# # print(aa)
# # C = []
# # for i in range(len(ee)):
# #     for j in range(len(aa)):
# #         c = np.mean(stime[i,j,:])
# #         C.append(c)
# # print(C)
# plt.scatter(ee,aa,c=np.mean(stime,axis=1),lw=3)
# plt.xlabel('$e_{bin}$')
# plt.ylabel('$a/a_{bin}$')
# plt.tight_layout()
# # plt.savefig(workdir+'/mean_stimes.png',bbox_inches="tight")




In [ ]:
# from myfunctions import Plotting0

# from myfunctions import PlottingLL
# for i,eb in enumerate(ebs):
#     for j,ap in enumerate(aps):
#         for k,mu in enumerate(mus):
#             print(stime[i,j,k,:])
#             PlottingLL.PlottingLL(eb, ap, mu,stime[i,j,k,:],Np) 
            
for i,mu in enumerate(mus):
    for j in range(0,Np):      
        
        Plotting0.Plotting0(ebs,aps,Na, Ne,stime[:,:,i,j].T,mu) 

In [ ]:
from myfunctions import Plotting0


for i,mu in enumerate(mus):
    for j in range(0,Np):      
        
        Plotting0.Plotting0(ebs,aps,Na, Ne,stime[:,:,i,j].T,mu) 

In [ ]:
stime[0,0,:,:]

In [ ]:
#     params = [(eb,ap,mu,Np) for eb in ebs for ap in aps for mu in mus]
params = []

a_array = np.zeros((Na,Ne))
stime_a = np.zeros((Na,Ne))
e_array = np.zeros((Na,Ne))

for i,e in enumerate(ebs):
    for j,mu in enumerate(mus):
        ac = HW_crit(e,mu)
        upper, lower = ac*1.15, ac*0.75
        av = np.append(np.linspace(1.,lower, Na2)[:-1],np.linspace(lower,upper,Na1))
        av = np.append(av, np.linspace(upper, 5.,Na2)[1:])
#             for a in av:
        for k,a in enumerate(av):
            params.append((e,a,mu,Np))
            a_array[k,i] = a
            e_array[k,i] = e
            stime_a[k,i] = np.mean(stime[i,k,0,:])

print(a_array)
print(e_array)
print(params)
print(stime_a)

In [ ]:
fig,ax=plt.subplots(1,1)
cp = ax.contourf(e_array, a_array, stime_a)
fig.colorbar(cp) # Add a colorbar to a plot

ab_s = np.zeros(Ne)
for i,eb in enumerate(ebs):
    ab_s[i] = 1.6 + 5.1*eb-2.22*(eb**2)+4.12*mu-4.27*eb*mu-5.09*(mu**2)+4.61*(eb**2)*mu**2
   #ab_s[i] = 2.278 + 3.824*eb - 1.71*(eb**2)

ax.plot(ebs,ab_s,'c', marker = "^",markersize = 7)
ax.set_xlabel('$e_b$')
ax.set_ylabel('$a_b(a_c$)')
# plt.title(' Mu {} Critical semimajor axis $a_c$ as a function of eccentricity $e_b$'.format(mu))
plt.show()